on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout self
    #   uses: actions/checkout@v2

    - name: Checkout funA
      uses: actions/checkout@v2
      with:
        repository: linustorvalds815/funB
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create and push branch
      run: |
        cd ${{ github.workspace }}
        ls -al
        git config --global user.name 'linustorvalds815'
        git config --global user.email '167972596+linustorvalds815@users.noreply.github.com'
        git checkout -b security/test
        git push -u origin security/test
