on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout self
    #   uses: actions/checkout@v2

    - name: Checkout funA
      uses: actions/checkout@v2
      with:
        repository: linustorvalds815/funB
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create branch and push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://linustorvalds815:$GITHUB_TOKEN@github.com/linustorvalds815/funB.git
        cd funB
        ls -al
        # git remote add origin https://linustorvalds815:$GITHUB_TOKEN@github.com/linustorvalds815/funB.git
        # git remote set-url origin https://linustorvalds815:$GITHUB_TOKEN@github.com/linustorvalds815/funB.git
        git config --global user.name 'linustorvalds815'
        git config --global user.email '167972596+linustorvalds815@users.noreply.github.com'
        git config --unset-all http.https://github.com/.extraheader
        git checkout -b security/test
        git remote -v
        # git push -u origin security/test -v
